on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *" # run every hour

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create snake
        uses: Platane/snk@v3
        with:
          # GitHub user name to read the contribution graph from (**required**)
          # using action context var `github.repository_owner` or specified user
          github_user_name: yasxEd

          # List of files to generate.
          # One file per line. Each output can be customized with options as query string.
          #
          # Supported options:
          # - palette:     A preset of color, one of [github, github-dark, github-light]
          # - color_snake: Color of the snake
          # - color_dots:  Coma separated list of dots color.
          #                The first one is 0 contribution, then it goes from the low contribution to the highest.
          #                Exactly 5 colors are expected.
          outputs: |
            dist/github-snake.svg?color_snake=#8a2be2&color_dots=#00ff00,#0000ff,#ff00ff,#ff0000,#ffff00
            dist/github-snake-dark.svg?palette=github-dark&color_snake=#8a2be2&color_dots=#00ff00,#0000ff,#ff00ff,#ff0000,#ffff00
            dist/ocean.gif?color_snake=#8a2be2&color_dots=#00ff00,#0000ff,#ff00ff,#ff0000,#ffff00

      - name: Push GitHub contribution grid snake to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
